### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by micuat** [lizvlx/UBERMORGEN#1]
![image](https://user-images.githubusercontent.com/1835081/115309502-add6af80-a16c-11eb-8d4f-264eec576c1c.png)

this is great!!

**Comment by lizvlx** [comment]
Yeah

Originally some British dudes were supposed to code so I don’t have to do all myself.
But
Then they fucked up and
Nothing worked, it just looked like it works but it was crashing browsers - and
-
Even apache on the server.
Fucking crazy.
Spend 1 week cleaning up their shite and reprogramming most of it myself.
They did not know ow to program, they were just using interfaces that produce
Code and glueing it together.
And the errors here are the ones that don’t cause browser overload so I stopped repairing the shit.
Seriously, I was so angry.
It really is true, wanna get something done right, gotta do it yourself.
Fucking Liverpool Biennial (ableist fuckers) wanted us to use these British web dudes.
Never fucking again.
If I need coders I get them from Bulgaria or such.
They at least code for reals.

**Comment by micuat** [comment]
I hope those who deserves it, those who dig into the code find this page and learn what's behind the scenes. I appreciate you sharing this. I recommend Japanese coders next time

**Comment by lizvlx** [comment]
I was planning on coding everything myself anyway. Thats like my ´favourite part in a way.
But this idiotic Liverpool Biennial, who are so full of themselves, they act like they are the
Thing but all they are is ableist wannabes and the worst is that curator we worked with, joasia,
She was ridiculing and abusing me for my autism for her personal gain and fun.
I really like the project, it was only made because of Christiane Paul, she is such a great 
Curator and person. Them Liverpool people, damn, worst I have experienced in like 10 years.
#dontshare - once we have gotten paid I might file a discrimination claim with them.

So really this is just between us. Only telling you coz you fellow cutie. No damn autocorrect.
Not cutie. A u t I e :D
